
-- 1）先构建一个用户样本；sql中以【每天发起用信申请的用户 + 用信申请时间】作为计算特征的目标人群；真实场景中以【调用特征用户当时的实际业务时间为准】
-- target_user只是服务于实时特征上线前，和后端结果回溯上线使用；
with target_user as (
    select id as apply_id, create_time as use_create_time,cust_no
    from hive_idc.oversea.ods_mx_aprv_approve_use_credit_apply_df
    where pt ='${dt}' -- yyymmdd格式
    and replace(substr(create_time,1,10) ,'-', '')  ='${dt}'
)
-- PART 1 : 第一部分特征
-- 2）调用实时特征时，对应用户历史订单行为（基于还款计划）；
-- and t2.update_time < t1.create_time   --窗口之前该用户的还款计划数据
-- and (t2.settled_time is null or t2.settled_time < t1.create_time)   --窗口之前该用户的还款计划数据
-- 在贷款订单逻辑：(t4.settled_time is null or t4.settled_time>t3.use_create_time) 未还或窗口期后还的
-- 在贷续借订单逻辑：(t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 除了第一笔订单,未还或窗口期后还的
-- 逾期账单的逻辑：t3.loan_end_date < substr(t3.use_create_time,1,10) and (t3.settled_time is null or substr(t3.settled_time,1,10)> t3.loan_end_date) 已过期未还 or 过期后还的
-- 到期账单逻辑：t3.loan_end_date <= substr(t3.use_create_time,1,10) 已过期所有
-- 提前结清：t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < t3.loan_end_date 已提前还

select * from (
select t3.apply_id
     ,t3.cust_no
     ,t3.use_create_time
    -- 最远一笔订单相关
     ,coalesce(count(if(t3.order_asc_rank=1 and t3.settled_time is not null and t3.settled_time < t3.use_create_time ,t3.id ,null)), -999) as multi_loan_order_info_furthestsingleorder_completetermcnt
     ,coalesce(round(count(if(t3.order_asc_rank=1 and t3.settled_time is not null and t3.settled_time < t3.use_create_time ,t3.id ,null))/count(if(t3.order_asc_rank=1, t3.id, null)), 6), -999) as multi_loan_order_info_furthestsingleorder_completetermratio
     ,coalesce(count(if(t3.order_asc_rank=1 and t3.settled_time is not null and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < t3.loan_end_date, t3.id ,null)), -999) as multi_loan_order_info_furthestsingleorder_completefutureduetermcnt
     ,coalesce(round(count(if(t3.order_asc_rank=1 and t3.settled_time is not null and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < t3.loan_end_date, t3.id ,null))/count(if(t3.order_asc_rank=1 and t3.settled_time is not null and t3.settled_time < t3.use_create_time ,t3.id ,null)), 6), -999) as multi_loan_order_info_furthestsingleorder_completefutureduetermratio
     ,coalesce(round(count(if(t3.order_asc_rank=1 and t3.settled_time is not null and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < t3.loan_end_date, t3.id ,null))/count(if(t3.order_asc_rank=1 and t3.loan_end_date >substr(t3.use_create_time,1,10) ,t3.id ,null)), 6), -999) as multi_loan_order_info_furthestsingleorder_prepayvsfuturebillingtermratio
     ,coalesce(max(if(t3.order_asc_rank=1, t3.periods, null)), -999) as multi_loan_order_info_furthestsingleorder_termscnt
     ,coalesce((datediff(max(if(t3.order_asc_rank=1, t3.loan_end_date, null)),min(if(t3.order_asc_rank=1, t3.loan_start_date, null))) + 1), -999) as multi_loan_order_info_furthestsingleorder_payoutdays
     ,coalesce(count(if(t3.order_asc_rank=1 and (t3.settled_time is null or t3.settled_time > t3.use_create_time) ,t3.id ,null)), -999) as multi_loan_order_info_furthestsingleorder_incompletetermcnt
     ,coalesce(round(count(if(t3.order_asc_rank=1 and t3.settled_time is not null and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < t3.loan_end_date,t3.id ,null))/max(if(t3.order_asc_rank=1,t3.periods, null)), 6), -999) as multi_loan_order_info_furthestsingleorder_prepayvsalltermratio
     ,coalesce(round(count(if(t3.order_asc_rank=1 and t3.settled_time is not null and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10)> t3.loan_end_date,t3.id ,null))/count(if(t3.order_asc_rank=1 and t3.settled_time is not null and t3.settled_time < t3.use_create_time ,t3.id ,null)), 6), -999) as multi_loan_order_info_furthestsingleorder_overduevscompletedtermratio
     ,coalesce(round(count(if(t3.order_asc_rank=1 and t3.loan_end_date < substr(t3.use_create_time,1,10) and (t3.settled_time is null or substr(t3.settled_time,1,10)> t3.loan_end_date),t3.id,null))/count(if(t3.order_asc_rank=1 and t3.loan_end_date <= substr(t3.use_create_time,1,10),t3.id,null)), 6), -999) as multi_loan_order_info_furthestsingleorder_overduevsbillingtermratio
     ,coalesce(round(count(if(t3.order_asc_rank=1 and t3.loan_end_date < substr(t3.use_create_time,1,10) and (t3.settled_time is null or substr(t3.settled_time,1,10)> t3.loan_end_date),t3.id,null))/max(if(t3.order_asc_rank=1,t3.periods, null)), 6), -999) as multi_loan_order_info_furthestsingleorder_overduetermratio
     ,coalesce(count(if(t3.order_asc_rank=1 and t3.loan_end_date < substr(t3.use_create_time,1,10) and (t3.settled_time is null or substr(t3.settled_time,1,10)> t3.loan_end_date),t3.id,null)), -999) as multi_loan_order_info_furthestsingleorder_overduetermcnt
     ,coalesce(datediff(min(if(t3.order_asc_rank=1 and t3.settled_time is not null and t3.settled_time < t3.use_create_time, cast(t3.settled_time as date), null)),min(if(t3.order_asc_rank=1,cast(t3.create_time as date), null))), -999) as multi_loan_order_info_furthestsingleorder_firstcompletedcreatedgap
     ,coalesce(datediff(cast(t3.use_create_time as date), min(if(t3.order_asc_rank=1,cast(t6.create_time as date), null))), -999) as multi_loan_order_info_furthestsingleorder_creatednowgap
     ,coalesce(max(if(t3.order_asc_rank=1 and substr(t6.create_time, 12, 2) in('11','12','13'), 1, 0)), -999) as multi_loan_order_info_furthestsingleorder_creatednoon
     ,coalesce(max(if(t3.order_asc_rank=1 and substr(t6.create_time, 12, 2) in('23','00','01','02','03','04'), 1, 0)), -999) as multi_loan_order_info_furthestsingleorder_creatednight
     ,coalesce(max(if(t3.order_asc_rank=1 and substr(t6.create_time, 12, 2) in('05','06','07','08','09','10'), 1, 0)), -999) as multi_loan_order_info_furthestsingleorder_createdmorning
     ,coalesce(max(if(t3.order_asc_rank=1 and substr(t6.create_time, 12, 2) in('18','19','20','21','22'), 1, 0)), -999) as multi_loan_order_info_furthestsingleorder_createdevening
     ,coalesce(max(if(t3.order_asc_rank=1 and substr(t6.create_time, 12, 2) in('14','15','16','17'), 1, 0)), -999) as multi_loan_order_info_furthestsingleorder_createdafternoon
     ,coalesce(round(count(if(t3.order_asc_rank=1 and t3.settled_time is not null and t3.settled_time < t3.use_create_time ,t3.id ,null))/count(if(t3.order_asc_rank=1 and t3.loan_end_date > substr(t3.use_create_time,1,10) ,t3.id ,null)), 6), -999) as multi_loan_order_info_furthestsingleorder_completevsfuturebillingtermratio
     ,coalesce(min(if(t3.order_asc_rank=1 and t3.settled_time is not null and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < t3.loan_end_date, datediff(cast(t3.loan_end_date as date), cast(substr(t3.settled_time,1,10) as date)),null)), -999) as multi_loan_order_info_furthestsingleorder_completeprepaydaysmin
     ,coalesce(round(avg(if(t3.order_asc_rank=1 and t3.settled_time is not null and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < t3.loan_end_date, datediff(cast(t3.loan_end_date as date), cast(substr(t3.settled_time,1,10) as date)),null)), 6), -999) as multi_loan_order_info_furthestsingleorder_completeprepaydaysmean
     ,coalesce(max(if(t3.order_asc_rank=1 and t3.settled_time is not null and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < t3.loan_end_date, datediff(cast(t3.loan_end_date as date), cast(substr(t3.settled_time,1,10) as date)),null)), -999) as multi_loan_order_info_furthestsingleorder_completeprepaydaysmax
     ,coalesce(round(sum(if(t3.order_asc_rank=1 and t3.settled_time is not null and t3.settled_time < t3.use_create_time and dayofweek(str_to_date(substr(t3.settled_time,1,10), '%Y-%m-%d')) IN (1, 7), t3.repaid_principal+t3.repaid_interest+t3.repaid_service_fee+t3.repaid_penalty,0))/sum(if(t3.order_asc_rank=1 and t3.settled_time is not null and t3.settled_time < t3.use_create_time , t3.repaid_principal+t3.repaid_interest+t3.repaid_service_fee+t3.repaid_penalty,0)), 6), -999) as multi_loan_order_info_furthestsingleorder_completeonweekendprincipalratio
     ,coalesce(round(count(if(t3.order_asc_rank=1 and t3.settled_time is not null and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < t3.loan_end_date,t3.id ,null))/count(if(t3.order_asc_rank=1 and t3.settled_time is not null and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10)<=t3.last_loan_end_date ,t3.id ,null)), 6), -999) as multi_loan_order_info_furthestsingleorder_billingprepayvscompletetermratio
     ,coalesce(round(count(if(t3.order_asc_rank=1 and t3.settled_time is not null and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < t3.loan_end_date,t3.id ,null))/count(if(t3.order_asc_rank=1 and t3.loan_end_date <= substr(t3.use_create_time,1,10),t3.id,null)), 6), -999) as multi_loan_order_info_furthestsingleorder_billingprepayvsbillingtermratio
    -- 最近第一笔订单相关
      ,coalesce(max(if(t3.order_desc_rank=1 and substr(t6.create_time, 12, 2) in('11','12','13'), 1, 0)), -999) as multi_loan_order_info_latest1singleorder_creatednoon
     ,coalesce(max(if(t3.order_desc_rank=1 and substr(t6.create_time, 12, 2) in('23','00','01','02','03','04'), 1, 0)), -999) as multi_loan_order_info_latest1singleorder_creatednight
     ,coalesce(max(if(t3.order_desc_rank=1 and substr(t6.create_time, 12, 2) in('05','06','07','08','09','10'), 1, 0)), -999) as multi_loan_order_info_latest1singleorder_createdmorning
     ,coalesce(max(if(t3.order_desc_rank=1 and substr(t6.create_time, 12, 2) in('18','19','20','21','22'), 1, 0)), -999) as multi_loan_order_info_latest1singleorder_createdevening
     ,coalesce(max(if(t3.order_desc_rank=1 and substr(t6.create_time, 12, 2) in('14','15','16','17'), 1, 0)), -999) as multi_loan_order_info_latest1singleorder_createdafternoon
     ,coalesce(max(if(t3.order_desc_rank=1,datediff(cast(t6.create_time as date),cast(t7.create_time as date)),null)), -999) as multi_loan_order_info_latest1singleorder_createdcalccreditgap
     ,coalesce(round(count(if(t3.order_desc_rank=1 and t3.settled_time is not null and t3.settled_time<t3.use_create_time and t3.loan_end_date >substr(t3.use_create_time,1,10),t3.id,null))/count(if(t3.order_desc_rank=1 and t3.loan_end_date >substr(t3.use_create_time,1,10),t3.id,null)), 6), -999) as multi_loan_order_info_latest1singleorder_completevsfuturebillingtermratio
     ,coalesce(round(count(if(t3.order_desc_rank=1 and t3.settled_time is not null and t3.settled_time<t3.use_create_time, t3.id, null))/max(if(t3.order_desc_rank=1,t3.periods, null)), 6), -999) as multi_loan_order_info_latest1singleorder_completetermratio
     ,coalesce(count(if(t3.order_desc_rank=1 and t3.settled_time is not null and t3.settled_time<t3.use_create_time, t3.id, null)), -999) as multi_loan_order_info_latest1singleorder_completetermcnt
     ,coalesce(min(if(t3.order_desc_rank=1 and t3.settled_time is not null and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < t3.loan_end_date, datediff(cast(t3.loan_end_date as date), cast(substr(t3.settled_time,1,10) as date)),null)), -999) as multi_loan_order_info_latest1singleorder_completeprepaydaysmin
     ,coalesce(round(avg(if(t3.order_desc_rank=1 and t3.settled_time is not null and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < t3.loan_end_date, datediff(cast(t3.loan_end_date as date), cast(substr(t3.settled_time,1,10) as date)),null)), 6), -999) as multi_loan_order_info_latest1singleorder_completeprepaydaysmean
     ,coalesce(max(if(t3.order_desc_rank=1 and t3.settled_time is not null and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < t3.loan_end_date, datediff(cast(t3.loan_end_date as date), cast(substr(t3.settled_time,1,10) as date)),null)), -999) as multi_loan_order_info_latest1singleorder_completeprepaydaysmax
     ,coalesce(round(count(if(t3.order_desc_rank=1 and t3.settled_time is not null and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < t3.loan_end_date, t3.id ,null))/count(if(t3.order_desc_rank=1 and t3.settled_time is not null and t3.settled_time < t3.use_create_time ,t3.id ,null)), 6), -999) as multi_loan_order_info_latest1singleorder_completefutureduetermratio
     ,coalesce(count(if(t3.order_desc_rank=1 and t3.settled_time is not null and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < t3.loan_end_date, t3.id ,null)), -999) as multi_loan_order_info_latest1singleorder_completefutureduetermcnt
     ,coalesce(round(count(if(t3.order_desc_rank=1 and t3.settled_time is not null and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < t3.loan_end_date,t3.id ,null))/count(if(t3.order_desc_rank=1 and t3.settled_time is not null and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10)<=t3.last_loan_end_date ,t3.id ,null)), 6), -999) as multi_loan_order_info_latest1singleorder_billingprepayvscompletetermratio
     ,coalesce(round(count(if(t3.order_desc_rank=1 and t3.settled_time is not null and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < t3.loan_end_date,t3.id ,null))/count(if(t3.order_desc_rank=1 and t3.loan_end_date <= substr(t3.use_create_time,1,10),t3.id,null)), 6), -999) as multi_loan_order_info_latest1singleorder_billingprepayvsbillingtermratio
     ,coalesce(datediff(cast(t3.use_create_time as date), min(if(t3.order_desc_rank=1,cast(t6.create_time as date), null))), -999) as multi_loan_order_info_latest1singleorder_creatednowgap
     ,coalesce(datediff(min(if(t3.order_desc_rank=1 and t3.settled_time is not null and t3.settled_time < t3.use_create_time, cast(t3.settled_time as date), null)),min(if(t3.order_desc_rank=1,cast(t3.create_time as date), null))), -999) as multi_loan_order_info_latest1singleorder_firstcompletedcreatedgap
     ,coalesce(count(if(t3.order_desc_rank=1 and (t3.settled_time is null or t3.settled_time > t3.use_create_time) ,t3.id ,null)), -999) as multi_loan_order_info_latest1singleorder_incompletetermcnt
     ,coalesce(count(if(t3.order_desc_rank=1 and t3.loan_end_date < substr(t3.use_create_time,1,10) and (t3.settled_time is null or substr(t3.settled_time,1,10)> t3.loan_end_date),t3.id,null)), -999) as multi_loan_order_info_latest1singleorder_overduetermcnt
     ,coalesce(round(count(if(t3.order_desc_rank=1 and t3.loan_end_date < substr(t3.use_create_time,1,10) and (t3.settled_time is null or substr(t3.settled_time,1,10)> t3.loan_end_date),t3.id,null))/max(if(t3.order_desc_rank=1,t3.periods, null)), 6), -999) as multi_loan_order_info_latest1singleorder_overduetermratio
     ,coalesce(round(count(if(t3.order_desc_rank=1 and t3.loan_end_date < substr(t3.use_create_time,1,10) and (t3.settled_time is null or substr(t3.settled_time,1,10)> t3.loan_end_date),t3.id,null))/count(if(t3.order_desc_rank=1 and t3.loan_end_date <= substr(t3.use_create_time,1,10),t3.id,null)), 6), -999) as multi_loan_order_info_latest1singleorder_overduevsbillingtermratio
     ,coalesce(round(count(if(t3.order_desc_rank=1 and t3.settled_time is not null and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10)> t3.loan_end_date,t3.id ,null))/count(if(t3.order_desc_rank=1 and t3.settled_time is not null and t3.settled_time < t3.use_create_time ,t3.id ,null)), 6), -999) as multi_loan_order_info_latest1singleorder_overduevscompletedtermratio
     ,coalesce((datediff(max(if(t3.order_desc_rank=1, t3.loan_end_date, null)),min(if(t3.order_desc_rank=1, t3.loan_start_date, null))) + 1), -999) as multi_loan_order_info_latest1singleorder_payoutdays
     ,coalesce(round(count(if(t3.order_desc_rank=1 and t3.settled_time is not null and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < t3.loan_end_date,t3.id ,null))/max(if(t3.order_desc_rank=1,t3.periods, null)), 6), -999) as multi_loan_order_info_latest1singleorder_prepayvsalltermratio
     ,coalesce(round(count(if(t3.order_desc_rank=1 and t3.settled_time is not null and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < t3.loan_end_date, t3.id ,null))/count(if(t3.order_desc_rank=1 and t3.loan_end_date >substr(t3.use_create_time,1,10) ,t3.id ,null)), 6), -999) as multi_loan_order_info_latest1singleorder_prepayvsfuturebillingtermratio
     ,coalesce(max(if(t3.order_desc_rank=1, t3.periods, null)), -999) as multi_loan_order_info_latest1singleorder_termscnt
     -- 最近第二笔订单相关
     ,coalesce(max(if(t3.order_desc_rank=2 and substr(t6.create_time, 12, 2) in('11','12','13'), 1, 0)), -999) as multi_loan_order_info_latest2singleorder_creatednoon
     ,coalesce(max(if(t3.order_desc_rank=2 and substr(t6.create_time, 12, 2) in('23','00','01','02','03','04'), 1, 0)), -999) as multi_loan_order_info_latest2singleorder_creatednight
     ,coalesce(max(if(t3.order_desc_rank=2 and substr(t6.create_time, 12, 2) in('05','06','07','08','09','10'), 1, 0)), -999) as multi_loan_order_info_latest2singleorder_createdmorning
     ,coalesce(max(if(t3.order_desc_rank=2 and substr(t6.create_time, 12, 2) in('18','19','20','21','22'), 1, 0)), -999) as multi_loan_order_info_latest2singleorder_createdevening
     ,coalesce(max(if(t3.order_desc_rank=2 and substr(t6.create_time, 12, 2) in('14','15','16','17'), 1, 0)), -999) as multi_loan_order_info_latest2singleorder_createdafternoon
     ,coalesce(max(if(t3.order_desc_rank=2,datediff(cast(t6.create_time as date),cast(t7.create_time as date)),null)), -999) as multi_loan_order_info_latest2singleorder_createdcalccreditgap
     ,coalesce(round(count(if(t3.order_desc_rank=2 and t3.settled_time is not null and t3.settled_time<t3.use_create_time and t3.loan_end_date >substr(t3.use_create_time,1,10),t3.id,null))/count(if(t3.order_desc_rank=2 and t3.loan_end_date >substr(t3.use_create_time,1,10),t3.id,null)), 6), -999) as multi_loan_order_info_latest2singleorder_completevsfuturebillingtermratio
     ,coalesce(round(count(if(t3.order_desc_rank=2 and t3.settled_time is not null and t3.settled_time<t3.use_create_time, t3.id, null))/max(if(t3.order_desc_rank=2,t3.periods, null)), 6), -999) as multi_loan_order_info_latest2singleorder_completetermratio
     ,coalesce(count(if(t3.order_desc_rank=2 and t3.settled_time is not null and t3.settled_time<t3.use_create_time, t3.id, null)), -999) as multi_loan_order_info_latest2singleorder_completetermcnt
     ,coalesce(min(if(t3.order_desc_rank=2 and t3.settled_time is not null and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < t3.loan_end_date, datediff(cast(t3.loan_end_date as date), cast(substr(t3.settled_time,1,10) as date)),null)), -999) as multi_loan_order_info_latest2singleorder_completeprepaydaysmin
     ,coalesce(round(avg(if(t3.order_desc_rank=2 and t3.settled_time is not null and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < t3.loan_end_date, datediff(cast(t3.loan_end_date as date), cast(substr(t3.settled_time,1,10) as date)),null)), 6), -999) as multi_loan_order_info_latest2singleorder_completeprepaydaysmean
     ,coalesce(max(if(t3.order_desc_rank=2 and t3.settled_time is not null and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < t3.loan_end_date, datediff(cast(t3.loan_end_date as date), cast(substr(t3.settled_time,1,10) as date)),null)), -999) as multi_loan_order_info_latest2singleorder_completeprepaydaysmax
     ,coalesce(round(count(if(t3.order_desc_rank=2 and t3.settled_time is not null and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < t3.loan_end_date, t3.id ,null))/count(if(t3.order_desc_rank=2 and t3.settled_time is not null and t3.settled_time < t3.use_create_time ,t3.id ,null)), 6), -999) as multi_loan_order_info_latest2singleorder_completefutureduetermratio
     ,coalesce(count(if(t3.order_desc_rank=2 and t3.settled_time is not null and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < t3.loan_end_date, t3.id ,null)), -999) as multi_loan_order_info_latest2singleorder_completefutureduetermcnt
     ,coalesce(round(count(if(t3.order_desc_rank=2 and t3.settled_time is not null and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < t3.loan_end_date,t3.id ,null))/count(if(t3.order_desc_rank=2 and t3.settled_time is not null and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10)<=t3.last_loan_end_date ,t3.id ,null)), 6), -999) as multi_loan_order_info_latest2singleorder_billingprepayvscompletetermratio
     ,coalesce(round(count(if(t3.order_desc_rank=2 and t3.settled_time is not null and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < t3.loan_end_date,t3.id ,null))/count(if(t3.order_desc_rank=2 and t3.loan_end_date <= substr(t3.use_create_time,1,10),t3.id,null)), 6), -999) as multi_loan_order_info_latest2singleorder_billingprepayvsbillingtermratio
     ,coalesce(datediff(cast(t3.use_create_time as date), min(if(t3.order_desc_rank=2,cast(t6.create_time as date), null))), -999) as multi_loan_order_info_latest2singleorder_creatednowgap
     ,coalesce(datediff(min(if(t3.order_desc_rank=2 and t3.settled_time is not null and t3.settled_time < t3.use_create_time, cast(t3.settled_time as date), null)),min(if(t3.order_desc_rank=2,cast(t3.create_time as date), null))), -999) as multi_loan_order_info_latest2singleorder_firstcompletedcreatedgap
     ,coalesce(count(if(t3.order_desc_rank=2 and (t3.settled_time is null or t3.settled_time > t3.use_create_time) ,t3.id ,null)), -999) as multi_loan_order_info_latest2singleorder_incompletetermcnt
     ,coalesce(count(if(t3.order_desc_rank=2 and t3.loan_end_date < substr(t3.use_create_time,1,10) and (t3.settled_time is null or substr(t3.settled_time,1,10)> t3.loan_end_date),t3.id,null)), -999) as multi_loan_order_info_latest2singleorder_overduetermcnt
     ,coalesce(round(count(if(t3.order_desc_rank=2 and t3.loan_end_date < substr(t3.use_create_time,1,10) and (t3.settled_time is null or substr(t3.settled_time,1,10)> t3.loan_end_date),t3.id,null))/max(if(t3.order_desc_rank=2,t3.periods, null)), 6), -999) as multi_loan_order_info_latest2singleorder_overduetermratio
     ,coalesce(round(count(if(t3.order_desc_rank=2 and t3.loan_end_date < substr(t3.use_create_time,1,10) and (t3.settled_time is null or substr(t3.settled_time,1,10)> t3.loan_end_date),t3.id,null))/count(if(t3.order_desc_rank=2 and t3.loan_end_date <= substr(t3.use_create_time,1,10),t3.id,null)), 6), -999) as multi_loan_order_info_latest2singleorder_overduevsbillingtermratio
     ,coalesce(round(count(if(t3.order_desc_rank=2 and t3.settled_time is not null and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10)> t3.loan_end_date,t3.id ,null))/count(if(t3.order_desc_rank=2 and t3.settled_time is not null and t3.settled_time < t3.use_create_time ,t3.id ,null)), 6), -999) as multi_loan_order_info_latest2singleorder_overduevscompletedtermratio
     ,coalesce((datediff(max(if(t3.order_desc_rank=2, t3.loan_end_date, null)),min(if(t3.order_desc_rank=2, t3.loan_start_date, null))) + 1), -999) as multi_loan_order_info_latest2singleorder_payoutdays
     ,coalesce(round(count(if(t3.order_desc_rank=2 and t3.settled_time is not null and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < t3.loan_end_date,t3.id ,null))/max(if(t3.order_desc_rank=2,t3.periods, null)), 6), -999) as multi_loan_order_info_latest2singleorder_prepayvsalltermratio
     ,coalesce(round(count(if(t3.order_desc_rank=2 and t3.settled_time is not null and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < t3.loan_end_date, t3.id ,null))/count(if(t3.order_desc_rank=2 and t3.loan_end_date >substr(t3.use_create_time,1,10) ,t3.id ,null)), 6), -999) as multi_loan_order_info_latest2singleorder_prepayvsfuturebillingtermratio
     ,coalesce(max(if(t3.order_desc_rank=2, t3.periods, null)), -999) as multi_loan_order_info_latest2singleorder_termscnt
    -- 未来90-180天订单特征、0-90天特征
      ,coalesce(count(if(t3.loan_end_date>=date_add(substr(t3.use_create_time, 1, 10),90) and t3.loan_end_date<=date_add(substr(t3.use_create_time, 1, 10),180) and (t3.settled_time is null or t3.settled_time>t3.use_create_time),t3.id,null)), -999) as multi_loan_order_info_multiloanrangefuture90dto180d_futurebillingunclearinstalcnt
     ,coalesce(count(if(t3.loan_end_date>date_add(substr(t3.use_create_time, 1, 10),0) and t3.loan_end_date<=date_add(substr(t3.use_create_time, 1, 10),90) and (t3.settled_time is null or t3.settled_time>t3.use_create_time),t3.id,null)), -999) as multi_loan_order_info_multiloanrangefuture0dto90d_futurebillingunclearinstalcnt
    -- 过去30天订单信息
      ,coalesce(count(distinct if(substr(t3.create_time,1,10) < substr(t3.use_create_time,1,10) and substr(t3.create_time,1,10)>=date_add(substr(t3.use_create_time,1,10),-30),t3.loan_no,null)), -999) as multi_loan_order_info_multiloan30dstat_payoutordercnt
     ,coalesce(count(distinct if(t3.order_asc_rank>1 and substr(t3.create_time,1,10) < substr(t3.use_create_time,1,10) and substr(t3.create_time,1,10)>=date_add(substr(t3.use_create_time,1,10),-30),t3.loan_no,null)), -999) as multi_loan_order_info_multiloan30dstat_payoutmultiloanordercnt
    -- 过去90天订单信息
      ,coalesce(count(if(substr(t3.settled_time,1,10) < substr(t3.use_create_time,1,10) and substr(t3.settled_time,1,10)>=date_add(substr(t3.use_create_time,1,10),-90), t3.id,null)), -999) as multi_loan_order_info_multiloannoloanclear90dstat_clearordercnt
     ,coalesce(round(count(if(substr(t3.settled_time,1,10) < substr(t3.use_create_time,1,10) and substr(t3.settled_time,1,10)>=date_add(substr(t3.use_create_time,1,10),-90), t3.id,null))/count(if(t3.loan_end_date <= substr(t3.use_create_time,1,10) and t3.loan_end_date>=date_add(substr(t3.use_create_time,1,10),-90), t3.id,null)), 6), -999) as multi_loan_order_info_multiloannoloanclear90dstat_clearorderratio
     ,coalesce(count(distinct if(substr(t3.create_time,1,10) < substr(t3.use_create_time,1,10) and substr(t3.create_time,1,10)>=date_add(substr(t3.use_create_time,1,10),-90),t3.loan_no,null)), -999) as multi_loan_order_info_multiloan90dstat_payoutordercnt
     ,coalesce(count(distinct if(t3.order_asc_rank>1 and substr(t3.create_time,1,10) < substr(t3.use_create_time,1,10) and substr(t3.create_time,1,10)>=date_add(substr(t3.use_create_time,1,10),-90),t3.loan_no,null)), -999) as multi_loan_order_info_multiloan90dstat_payoutmultiloanordercnt
    -- 过去180天订单信息
      ,coalesce(count(if(substr(t3.settled_time,1,10) < substr(t3.use_create_time,1,10) and substr(t3.settled_time,1,10)>=date_add(substr(t3.use_create_time,1,10),-180), t3.id,null)), -999) as multi_loan_order_info_multiloannoloanclear180dstat_clearordercnt
     ,coalesce(round(count(if(substr(t3.settled_time,1,10) < substr(t3.use_create_time,1,10) and substr(t3.settled_time,1,10)>=date_add(substr(t3.use_create_time,1,10),-180), t3.id,null))/count(if(t3.loan_end_date <= substr(t3.use_create_time,1,10) and t3.loan_end_date>=date_add(substr(t3.use_create_time,1,10),-180), t3.id,null)), 6), -999) as multi_loan_order_info_multiloannoloanclear180dstat_clearorderratio
    -- 在贷、续借订单的几个特征(loan_info表中settled_time代表用户订单整笔结清时间)：MEXICO_MULTI_LOAN_ORDER_INFO
      ,coalesce(count(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.loan_end_date < substr(t3.use_create_time,1,10) and (t3.settled_time is null or substr(t3.settled_time,1,10)> t3.loan_end_date), t3.id,null)), -999) as multi_loan_order_info_inloanorders_overduetermcnt
     ,coalesce(count(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.settled_time<t3.use_create_time, t3.id, null)), -999) as multi_loan_order_info_inloanorders_completetermcnt
     ,coalesce(round(count(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.settled_time<t3.use_create_time, t3.id, null))/count(if(t4.settled_time is null or t4.settled_time>t3.use_create_time, t3.id, null)), 6), -999) as multi_loan_order_info_inloanorders_completetermratio
     ,coalesce(sum(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.settled_time<t3.use_create_time, t3.repaid_principal, 0)), -999) as multi_loan_order_info_inloanorders_completeprincipal
     ,coalesce(round(count(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.loan_end_date < substr(t3.use_create_time,1,10) and (t3.settled_time is null or substr(t3.settled_time,1,10)> t3.loan_end_date),t3.id,null))/count(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.settled_time<t3.use_create_time,t3.id,null)), 6), -999) as multi_loan_order_info_inloanorders_overduevscompletetermratio
     ,coalesce(round(count(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.loan_end_date < substr(t3.use_create_time,1,10) and (t3.settled_time is null or substr(t3.settled_time,1,10)> t3.loan_end_date),t3.id,null))/count(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.loan_end_date<=substr(t3.use_create_time,1,10),t3.id,null)), 6), -999) as multi_loan_order_info_inloanorders_overduevsbillingtermratio
     ,coalesce(round(stddev(datediff(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.periods =1,cast(t3.create_time as date),null),if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.periods =1,cast(t7.create_time as date),null))), 6), -999) as multi_loan_order_info_inloanorders_calccreditgapstd
     ,coalesce(min(datediff(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.periods =1,cast(t3.create_time as date),null),if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.periods =1,cast(t7.create_time as date),null))), -999) as multi_loan_order_info_inloanorders_calccreditgapmin
     ,coalesce(round(avg(datediff(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.periods =1,cast(t3.create_time as date),null),if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.periods =1,cast(t7.create_time as date),null))), 6), -999) as multi_loan_order_info_inloanorders_calccreditgapmean
     ,coalesce(max(datediff(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.periods =1,cast(t3.create_time as date),null),if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.periods=1,cast(t7.create_time as date),null))), -999) as multi_loan_order_info_inloanorders_calccreditgapmax
     ,coalesce(round(count(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.loan_end_date < substr(t3.use_create_time,1,10) and (t3.settled_time is null or substr(t3.settled_time,1,10)> t3.loan_end_date), t3.id,null))/count(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.settled_time<t3.use_create_time, t3.id, null)), 6), -999) as multi_loan_order_info_multiloanorders_overduevscompletetermratio
     ,coalesce(round(count(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and t3.loan_end_date < substr(t3.use_create_time,1,10) and (t3.settled_time is null or substr(t3.settled_time,1,10)> t3.loan_end_date), t3.id,null))/count(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and t3.loan_end_date <= substr(t3.use_create_time,1,10),t3.id,null)), 6), -999) as multi_loan_order_info_multiloanorders_overduevsbillingtermratio
     ,coalesce(count(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and t3.loan_end_date < substr(t3.use_create_time,1,10) and (t3.settled_time is null or substr(t3.settled_time,1,10)> t3.loan_end_date), t3.id,null)), -999) as multi_loan_order_info_multiloanorders_overduetermcnt
     ,coalesce(round(stddev(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and t3.periods=1, t4.real_loan_amt,0)), 6), -999) as multi_loan_order_info_multiloanorders_orderprincipalstd
     ,coalesce(round(count(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and t3.settled_time<t3.use_create_time, t3.id, null))/count(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1, t3.id, null)), 6), -999) as multi_loan_order_info_multiloanorders_completetermratio
     ,coalesce(count(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and t3.settled_time<t3.use_create_time, t3.id, null)), -999) as multi_loan_order_info_multiloanorders_completetermcnt
     ,coalesce(sum(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and t3.settled_time<t3.use_create_time, t3.repaid_principal, 0)), -999) as multi_loan_order_info_multiloanorders_completeprincipal
     ,coalesce(round(stddev(datediff(if((t4.settled_time is null or t4.settled_time>t3.use_create_time)  and t3.order_asc_rank>1 and t3.periods =1,cast(t3.create_time as date),null),if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and t3.periods =1,cast(t7.create_time as date),null))), 6), -999) as multi_loan_order_info_multiloanorders_calccreditgapstd
     ,coalesce(min(datediff(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and t3.periods =1,cast(t3.create_time as date),null),if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and t3.periods =1,cast(t7.create_time as date),null))), -999) as multi_loan_order_info_multiloanorders_calccreditgapmin
     ,coalesce(round(avg(datediff(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and t3.periods =1,cast(t3.create_time as date),null),if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and t3.periods=1,cast(t7.create_time as date),null))), 6), -999) as multi_loan_order_info_multiloanorders_calccreditgapmean
     ,coalesce(max(datediff(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and t3.periods =1,cast(t3.create_time as date),null),if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and t3.periods =1,cast(t7.create_time as date),null))), -999) as multi_loan_order_info_multiloanorders_calccreditgapmax
    -- 在贷订单另外一批：MEXICO_MULTI_LOAN_IN_LOAN_ORDER
      ,coalesce(count(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < date_add(t3.loan_end_date,-15),t3.id,null)), -999) as multi_loan_in_loan_order_all_advanceget15days_completedadvanceinstalcnt
     ,coalesce(round(count(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < date_add(t3.loan_end_date,-15),t3.id,null))/count(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < t3.loan_end_date,t3.id,null)), 6), -999) as multi_loan_in_loan_order_all_advanceget15days_completedadvanceinstaloverallcompletedadvanceratio
     ,coalesce(round(count(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < date_add(t3.loan_end_date,-15),t3.id,null))/count(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and (t3.settled_time < t3.use_create_time or t3.loan_end_date <= substr(t3.use_create_time,1,10)),t3.id,null)), 6), -999) as multi_loan_in_loan_order_all_advanceget15days_completedadvanceinstaloverdueorcompletedratio
     ,coalesce(count(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < date_add(t3.loan_end_date,-7),t3.id,null)), -999) as multi_loan_in_loan_order_all_advanceget7days_completedadvanceinstalcnt
     ,coalesce(round(count(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < date_add(t3.loan_end_date,-7),t3.id,null))/count(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < t3.loan_end_date,t3.id,null)), 6), -999) as multi_loan_in_loan_order_all_advanceget7days_completedadvanceinstaloverallcompletedadvanceratio
     ,coalesce(round(count(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < date_add(t3.loan_end_date,-7),t3.id,null))/count(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and (t3.settled_time < t3.use_create_time or t3.loan_end_date <= substr(t3.use_create_time,1,10)),t3.id,null)), 6), -999) as multi_loan_in_loan_order_all_advanceget7days_completedadvanceinstaloverdueorcompletedratio
     ,coalesce(count(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < date_add(t3.loan_end_date,-3),t3.id,null)), -999) as multi_loan_in_loan_order_all_advanceget3days_completedadvanceinstalcnt
     ,coalesce(round(count(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < date_add(t3.loan_end_date,-3),t3.id,null))/count(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < t3.loan_end_date,t3.id,null)), 6), -999) as multi_loan_in_loan_order_all_advanceget3days_completedadvanceinstaloverallcompletedadvanceratio
     ,coalesce(round(count(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < date_add(t3.loan_end_date,-3),t3.id,null))/count(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and (t3.settled_time < t3.use_create_time or t3.loan_end_date <= substr(t3.use_create_time,1,10)),t3.id,null)), 6), -999) as multi_loan_in_loan_order_all_advanceget3days_completedadvanceinstaloverdueorcompletedratio
     ,coalesce(count(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < t3.loan_end_date, t3.id,null)), -999) as multi_loan_in_loan_order_all_completedadvanceinstalcnt
     ,coalesce(round(count(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) < t3.loan_end_date,t3.id,null))/count(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and (t3.settled_time < t3.use_create_time or t3.loan_end_date <= substr(t3.use_create_time,1,10)),t3.id,null)), 6), -999) as multi_loan_in_loan_order_all_completedadvanceinstalratio
     ,coalesce(round(sum(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and t3.settled_time < t3.use_create_time and substr(t3.settled_time,1,10) >= date_add(t3.loan_end_date,-30) and substr(t3.settled_time,1,10) < date_add(t3.loan_end_date,0) ,t3.repaid_principal,0))/sum(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and t3.settled_time < t3.use_create_time,t3.repaid_principal,0)), 6), -999) as multi_loan_in_loan_order_all_completedadvanceloanamountovercompletedratioforfirstmonth
     ,coalesce(count(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and t3.settled_time < t3.use_create_time,t3.id,null)), -999) as multi_loan_in_loan_order_all_completedinstalcnt
     ,coalesce(round(count(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and t3.settled_time < t3.use_create_time,t3.id,null))/count(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1,t3.id,null)), 6), -999) as multi_loan_in_loan_order_all_completedinstalratio
     ,coalesce(sum(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and t3.settled_time < t3.use_create_time,t3.repaid_principal,0)), -999) as multi_loan_in_loan_order_all_completedloanamount
     ,coalesce(round(avg(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and t3.periods=1,datediff(cast(t3.use_create_time as date), cast(t6.create_time as date)),null)), 6), -999) as multi_loan_in_loan_order_all_createdorderdaysgapmathcount_avg
     ,coalesce(max(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and t3.periods=1,datediff(cast(t3.use_create_time as date), cast(t6.create_time as date)),null)), -999) as multi_loan_in_loan_order_all_createdorderdaysgapmathcount_max
     ,coalesce(round(stddev(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and t3.periods=1,datediff(cast(t3.use_create_time as date), cast(t6.create_time as date)),null)), 6), -999) as multi_loan_in_loan_order_all_createdorderdaysgapmathcount_std
     ,coalesce(max(if((t4.settled_time is null or t4.settled_time>t3.use_create_time) and t3.order_asc_rank>1 and t3.loan_end_date < substr(t3.use_create_time,1,10) and (t3.settled_time is null or substr(t3.settled_time,1,10)> t3.loan_end_date), datediff(cast(t3.loan_end_date as date), cast(t6.create_time as date)),null)), -999) as multi_loan_in_loan_order_all_lastoverdueinstalrisktimegap

from
    (
        select t1.apply_id
             ,t1.cust_no
             ,t1.use_create_time
             ,t2.id
             ,t2.loan_no
             ,t2.settled_time
             ,t2.create_time
             ,t2.loan_end_date
             ,t2.loan_start_date
             ,t2.repaid_principal
             ,t2.repaid_interest
             ,t2.repaid_service_fee
             ,t2.repaid_penalty
             ,dense_rank()over(partition by t1.cust_no,t1.use_create_time order by ala.create_time asc) as order_asc_rank -- 升序排序，1即为最远一笔
          ,dense_rank()over(partition by t1.cust_no,t1.use_create_time order by ala.create_time desc) as order_desc_rank -- 降序排序，1即为最近一笔
          ,last_value(t2.loan_end_date) over (partition by t1.cust_no,t1.use_create_time,t2.loan_no order by t2.loan_end_date ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) as last_loan_end_date -- 该笔订单的整体到期时间
          ,t2.periods
        from target_user as t1
                 left join (
            select *
            from hive_idc.oversea.ods_mx_ast_asset_repay_plan_df
            where pt ='${dt}' -- yyymmdd格式
              and replace(substr(create_time,1,10) ,'-', '') <='${dt}'
              and repay_plan_status != 4
        ) as t2
                           on t1.cust_no = t2.cust_no
                 left join (select * from hive_idc.oversea.ods_mx_ast_asset_loan_info_df where pt ='${dt}') ali ON t2.loan_no = ali.loan_no
                 left join (select * from hive_idc.oversea.ods_mx_ast_asset_loan_apply_df where pt ='${dt}') ala ON ali.loan_apply_no = ala.loan_apply_no
        where t2.create_time < t1.use_create_time
    ) as t3
        left join (select loan_no,loan_apply_no,settled_time,real_loan_amt from hive_idc.oversea.ods_mx_ast_asset_loan_info_df where pt ='${dt}' and loan_status != 4) as t4 on t3.loan_no = t4.loan_no
        left join (select loan_apply_no,seq_no from hive_idc.oversea.ods_mx_ast_asset_loan_apply_df where pt ='${dt}') as t5 on t4.loan_apply_no = t5.loan_apply_no
        left join (select asset_id,create_time,credit_apply_id from hive_idc.oversea.ods_mx_aprv_approve_use_credit_apply_df where pt ='${dt}') as t6 on t5.seq_no = t6.asset_id
        left join (select id,create_time from hive_idc.oversea.ods_mx_aprv_approve_credit_apply_df where pt='${dt}' ) as t7 on t6.credit_apply_id = t7.id
group by t3.apply_id,t3.cust_no,t3.use_create_time) t
-- where use_create_time>'2026-02-02 09:56:00';